---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - cronjob
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - magnit.magnit.com
  resources:
  - crontabs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - magnit.magnit.com
  resources:
  - crontabs/finalizers
  verbs:
  - update
- apiGroups:
  - magnit.magnit.com
  resources:
  - crontabs/status
  verbs:
  - get
  - patch
  - update
